# Generated by Django 5.0.7 on 2024-09-16 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task_description_task_due_date_task_priority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='user',
        ),
    ]
